[default]
    DEBUG = false
    HOST = "127.0.0.1"
    PORT = 8000
    SITE_URL = "https://ai-agent-backend.local"
    SITE_NAME = "AI Agent Backend"

    [default.openrouter]
        base_url = "https://openrouter.ai/api/v1"

    [default.assistant]
        allowed_models = [
            "openrouter/polaris-alpha",
            "nvidia/nemotron-nano-12b-v2-vl:free",
            # "qwen/qwen2.5-vl-32b-instruct:free",
            # "google/gemma-3-4b-it:free",
            # "google/gemma-3-12b-it:free",
            # "google/gemini-flash-1.5-8b",
            # "meta-llama/llama-4-scout:free",
        ]
        default_model = "nvidia/nemotron-nano-12b-v2-vl:free"
